/*
 * This file was generated by the Gradle 'init' task.
 */

version = "1.0.0"

plugins {
    id("demo.kotlin-application-conventions")
    id("com.jung.demoBuildPlugin")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("demo.app.AppKt")
}

//configure<DemoBuildExtension> {
//    message = "Set message from app module"
//}

demo {
    message = "Set message from app module"
}

